# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.4.x version
  - 5.4
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 5.4
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text

notifications:
  email:
    recipients:
      - o.baranetskiy@imagecms.net
      
    on_success: [always] # default: change
    on_failure: [always] # default: always|never|change













#sudo: false

#language: php

#php:
 #- 5.4
 #- 5.5
 #- 5.6
 #- nightly
 #- hhvm

#matrix:
# allow_failures:
#  - php: nightly

